#!/usr/bin/python3

from sys import argv


def factorize_number(number):
    i = 2

    if number < 2:
        return

    print()
    print(number, "<- value before factorization")

    while number % i:
        i += 1

    print("{:.0f} = {:.0f} * {:.0f}".format(number, number / i, i))
    print(number, "<- value after factorization")
    print()


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize_number(value)
            line = file.readline()
except:
    pass

